export const elements = {
    pages: { stats: document.getElementById('stats-page'), dashboard: document.getElementById('dashboard-page'), logHours: document.getElementById('log-hours-page'), recent: document.getElementById('recent-page'), skills: document.getElementById('skills-page'), settings: document.getElementById('settings-page'), about: document.getElementById('about-page') },
    nav: { stats: document.getElementById('nav-stats'), dashboard: document.getElementById('nav-dashboard'), logHours: document.getElementById('nav-log-hours'), recent: document.getElementById('nav-recent'), skills: document.getElementById('nav-skills'), settings: document.getElementById('nav-settings'), about: document.getElementById('nav-about') },
    totalLevelValue: document.getElementById('total-level-value'),
    statGrid: document.getElementById('stat-grid-main'),
    skillSelect: document.getElementById('skill-select'),
    hoursInput: document.getElementById('hours-input'),
    addHoursBtn: document.getElementById('add-hours-btn'),
    editSkillsContainer: document.getElementById('edit-skills-container'),
    charNameInput: document.getElementById('char-name-input'),
    saveEditsBtn: document.getElementById('save-edits-btn'),
    addSkillBtn: document.getElementById('add-skill-btn'),
    tooltip: document.getElementById('tooltip'),
    saveToFileBtn: document.getElementById('save-to-file-btn'),
    loadFromFileBtn: document.getElementById('load-from-file-btn'),
    fileLoaderInput: document.getElementById('file-loader-input'),
    recentActivityContainer: document.getElementById('recent-activity-container'),
    recentViewSelect: document.getElementById('recent-view-select'),
    hardModeToggle: document.getElementById('hard-mode-toggle'),
    themeToggle: document.getElementById('theme-toggle'),
    moreBtn: document.getElementById('nav-more'),
    moreDropdown: document.getElementById('more-dropdown'),
    skillChartCanvas: document.getElementById('skill-chart'),
};